### ISSUE TITLE
Gox not found

### ISSUE THREAD

**Issue by voxelias** [norman784/gaiku#2]
Hi! Can't compile anything because of this
`gox = { path = "../../gox" }`

If I uncomment `gox = "0.2.0"`, then compilation fails

```
error[E0599]: no method named `get_pixel_f32` found for reference `&gox::block::Block` in the current scope
  --> gaiku-3d/src/formats/gox.rs:48:60
   |
48 | ...                   colors.get_pixel_f32(x, y, z).into(),
   |                              ^^^^^^^^^^^^^ help: there is an associated function with a similar name: `get_pixel`

```

What version of gox there should be? If there is a reason of having some specific version, that can not be handled by cargo, maybe consider using a git module?

**Comment by norman784** [comment]
Hi, sorry for that, I was doing some changes in both crates at the time so that's why I used a relative path instead of the crates.io version, I pushed the changes so you can now use the updated gox crate.

**Comment by voxelias** [comment]
Now it panics:
```
cargo run --example heightmap
    Finished dev [unoptimized + debuginfo] target(s) in 0.03s
     Running `/home/elias/amethyst/gaiku/target/debug/examples/heightmap`
PNG w: 256 h: 256 bit_depth: Eight buffer_size: 262144 color_type: RGBA
thread 'main' panicked at 'attempt to multiply with overflow', gaiku-3d/src/bakers/heightmap.rs:21:26
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

```
RUST_BACKTRACE=1 cargo run --example heightmap
    Finished dev [unoptimized + debuginfo] target(s) in 0.04s
     Running `/home/elias/amethyst/gaiku/target/debug/examples/heightmap`
PNG w: 256 h: 256 bit_depth: Eight buffer_size: 262144 color_type: RGBA
thread 'main' panicked at 'attempt to multiply with overflow', gaiku-3d/src/bakers/heightmap.rs:21:26
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1076
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1537
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:486
  11: rust_begin_unwind
             at src/libstd/panicking.rs:388
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:101
  13: core::panicking::panic
             at src/libcore/panicking.rs:56
  14: <gaiku_3d::bakers::heightmap::HeightMapBaker as gaiku_common::Baker>::bake
             at gaiku-3d/src/bakers/heightmap.rs:21
  15: heightmap::read
             at gaiku-3d/examples/heightmap.rs:27
  16: heightmap::main
             at gaiku-3d/examples/heightmap.rs:51
  17: std::rt::lang_start::{{closure}}
             at /home/elias/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/rt.rs:67
  18: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  19: std::panicking::try::do_call
             at src/libstd/panicking.rs:297
  20: std::panicking::try
             at src/libstd/panicking.rs:274
  21: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  22: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  23: std::rt::lang_start
             at /home/elias/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/rt.rs:67
  24: main
  25: __libc_start_main
  26: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by norman784** [comment]
Yeah, currently is somehow broken the library, I did a quick but not intensive check and seems that now voxel and heightmap works, but marching cube baker is broken.
